import { Metadata } from "next";

import { Suspense } from "react";

import TACComponent from "./TACComponent";

// Metadata
export const metadata: Metadata = {
  title: "Terms & Condition",
  description: "Generated by create next app",
};

export default function PrivacyPolicy() {
  return (
    <Suspense>
      <TACComponent />
    </Suspense>
  );
}