import { Metadata } from "next";

import { Suspense } from "react";

import ShippingDeliverComponent from "./ShippingDeliveryComponent";

// Metadata
export const metadata: Metadata = {
  title: "Shipping Delivery",
  description: "Generated by create next app",
};

export default function ShippingDelivery() {
  return (
    <Suspense>
      <ShippingDeliverComponent />
    </Suspense>
  );
}